
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:26 (project)"
    message: |
      The target system is: Generic - 1 - arm
      The host system is: Windows - 10.0.22631 - AMD64
...
